homepage:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Default:index }

#_login_route:
#    pattern:  /login
#    defaults: { _controller: AcmeDemoBundle:Default:login }

#_login_check_route:
#    pattern:  /login/check

#_logout_route:
#    pattern:  /logout
