product:
    pattern:  /
    defaults: { _controller: "AcmeProductBundle:Product:index" }

product_show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmeProductBundle:Product:show" }

product_new:
    pattern:  /new
    defaults: { _controller: "AcmeProductBundle:Product:new" }

product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeProductBundle:Product:edit" }

product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeProductBundle:Product:delete" }
    requirements: { _method: post|delete }
